name: AdventOfCode

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history

      - name: Detect Changed Directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^day' | uniq)
          echo "CHANGED_DIRS=${CHANGED_DIRS}" >> $GITHUB_ENV

      - name: Build and Run Updated Days
        if: env.CHANGED_DIRS != ''
        run: |
          for dir in $CHANGED_DIRS; do
            echo "Building and running $dir"
            (cd $dir && ./configure && make && ./main)
          done