name: AdventOfCode

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read Current Day
      id: read_day
      run: |
        current_day=$(cat current_day.txt)
        echo "Current day is $current_day"
        echo "CURRENT_DAY=$current_day" >> $GITHUB_ENV

    - name: Build and Run Current Day
      run: |
        cd $CURRENT_DAY
        chmod +x ./configure
        ./configure
        make
        ./main